spring:
  datasource:
    username: debuggeandoideas-prod
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
    url: jdbc:postgresql://localhost:5432/companies
    password: HGASXTYW634GFEYHY6gs
